module.exports = {
  APP_NAME: "Padel GO",
  TG_CHANNEL: "@PadelMateBY",
  TG_CHAT: "@PadelMateChat",
  MIN_LEVEL: 1.0,
  MAX_LEVEL: 4.0,
  LEVEL_STEP: 1.0,
  RATING: {
    K_CALIBRATION: 50,
    K_INTERMEDIATE: 40,
    K_ESTABLISHED: 32,
    CALIBRATION_MATCHES: 10,
    INTERMEDIATE_MATCHES: 30,
    BLOWOUT_MULTIPLIER: 1.15,
    TIGHT_MULTIPLIER: 0.90,
    THREE_SET_MULTIPLIER: 1.10,
    WEEKLY_ACTIVE_BONUS: 5,
    MONTHLY_ACTIVE_BONUS: 10,
    FIRST_MATCH_BONUS: 20,
    NO_SHOW_PENALTY: -15,
  },
  LEVELS: [
    { min: 0, max: 2500, level: 1.0, category: "D", name: "Новичок", ntrp: "1.0–2.5" },
    { min: 2501, max: 3500, level: 2.0, category: "C", name: "Любитель", ntrp: "3.0–3.5" },
    { min: 3501, max: 4500, level: 3.0, category: "B", name: "Продвинутый", ntrp: "4.0–4.5" },
    { min: 4501, max: 5000, level: 4.0, category: "A", name: "Сильный", ntrp: "5.0+" },
  ],
  XP_LEVELS: [
    { min: 0, icon: "🌱", name: "Новичок" },
    { min: 200, icon: "🌿", name: "Активист" },
    { min: 500, icon: "🌳", name: "Регуляр" },
    { min: 1000, icon: "⭐", name: "Ветеран" },
    { min: 2000, icon: "💎", name: "Мастер" },
    { min: 3500, icon: "👑", name: "Легенда" },
  ],
};
