module.exports = {
  APP_NAME: "PadelMate",
  TG_CHANNEL: "@PadelMateBY",
  TG_CHAT: "@PadelMateChat",
  CITIES: ["Минск", "Брест", "Гродно"],
  CITY_MAP: {
    MINSK: "Минск",
    BREST: "Брест",
    GRODNO: "Гродно",
  },
  MIN_LEVEL: 1.0,
  MAX_LEVEL: 4.0,
  LEVEL_STEP: 0.5,
  RATING: {
    K_CALIBRATION: 50,
    K_INTERMEDIATE: 40,
    K_ESTABLISHED: 32,
    CALIBRATION_MATCHES: 10,
    INTERMEDIATE_MATCHES: 30,
    BLOWOUT_MULTIPLIER: 1.15,
    TIGHT_MULTIPLIER: 0.90,
    THREE_SET_MULTIPLIER: 1.10,
    WEEKLY_ACTIVE_BONUS: 5,
    MONTHLY_ACTIVE_BONUS: 10,
    FIRST_MATCH_BONUS: 20,
    NO_SHOW_PENALTY: -15,
  },
  LEVELS: [
    { min: 0, max: 999, level: 1.0, name: "Новичок" },
    { min: 1000, max: 1199, level: 1.5, name: "Начинающий" },
    { min: 1200, max: 1399, level: 2.0, name: "Любитель" },
    { min: 1400, max: 1599, level: 2.5, name: "Средний" },
    { min: 1600, max: 1799, level: 3.0, name: "Продвинутый" },
    { min: 1800, max: 1999, level: 3.5, name: "Сильный" },
    { min: 2000, max: 9999, level: 4.0, name: "Эксперт" },
  ],
  XP_LEVELS: [
    { min: 0, icon: "🌱", name: "Новичок" },
    { min: 200, icon: "🌿", name: "Активист" },
    { min: 500, icon: "🌳", name: "Регуляр" },
    { min: 1000, icon: "⭐", name: "Ветеран" },
    { min: 2000, icon: "💎", name: "Мастер" },
    { min: 3500, icon: "👑", name: "Легенда" },
  ],
};
